name: pytest

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    initial:
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
        - name: Check out repository code
          uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version-file: "pyproject.toml"
              
        - name: Install the project
          run: uv sync --all-extras --dev
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        needs: initial

        steps:
        - name: check format with flake8
          run: flake8 .

    test:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        needs: test

        steps:
        - name: Run tests
          env:
              PYTHONPATH: ${{ github.workspace }}
          run: uv run pytest tests
